### ISSUE TITLE
sturmreader or beru for ubuntu touch 15.04

### ISSUE THREAD

**Issue by josevidalrt** [TronFortyTwo/sturmreader#16]
Hello, I've seen that sturmreader is a fork de beru. Until recently beru worked on my ubuntu touch 15.04, but it was uninstalled and I don't have the .click to reinstall it. I know that sturmreader works well on ubuntu touch 16.04 and that ubports is doing a great job, but at the moment I prefer to stay on ubuntu 15.04. I have tried to compile the beru source code for ubuntu touch 15.04 in the arm architecture, but I only got it on i386. I've also read sturmreader's readme.md file but I can't understand how to compile it for arm architecture. I have also tried with clickable and sdk (it still works for me) but I can't get the .click. Can you help me? What escapes me?
Thank you.

**Comment by TronFortyTwo** [comment]
Probably the current release codebase will fail to build on vivid. Try building an old release still developed for vivid (such as 2.0.4 or 2.0.5), you should find it at commit [52f17b07ae14aee6e01dd99d603d56c713e43b8d]
