### ISSUE TITLE
Lost Library and can't add Books after update to 2.0.7

### ISSUE THREAD

**Issue by ghost** [TronFortyTwo/sturmreader#17]
I find no way to import my books again after the update to 2.0.7. (sturmreader+)

**Comment by ghost** [comment]
The folder for Sturm Reader ~/.lokal/share/sturmreader.emanuelesorce/Bücher works.
Whitch is the folder for Sturm Reader +?

**Comment by TronFortyTwo** [comment]
The + version is considered to be a completely different app than the standard version. The books won't move from one to another. If you were using the 2.0.6 non plus version, just continue using the non plus app with version 2.0.7

**Comment by ghost** [comment]
I always used the + version. After the update to 2.0.7. my library was empty and I found no way to import my books again. Opening a .epub directly isn't possible neither. I can't find any info which folder I should use..
That why I moved to the to the non + version.

**Comment by ghost** [comment]
By the way, I use Ubuntu Touch.

**Comment by TronFortyTwo** [comment]
Oh I see thank you for the report. BTW your books should be in ~/.lokal/share/sturmreader.plus.emanuelesorce/Bücher

**Comment by TronFortyTwo** [comment]
Looks like the + version tries to use the non plus database, I'll try to fix it asap

**Comment by TronFortyTwo** [comment]
This issue has been fixed with the last update of the plus version.
