### ISSUE TITLE
Support for AMD64 ARM64

### ISSUE THREAD

**Issue by ghost** [TronFortyTwo/sturmreader#18]
Would be great using sturmreader on AMD/ARM64 Ubuntu Touch devices like the Oneplus 3T, Xperia X and Pinephone
Any plans for that?

**Comment by TronFortyTwo** [comment]
Sure it would be great! I have to study how to do it thought. Thanks

**Comment by TronFortyTwo** [comment]
version 2.0.8 supports arm64 and amd64. Thanks for pointing it out!

**Comment by ghost** [comment]
Thanks. Sadly the app crashs immediately after opening.
I get no log file.

**Comment by TronFortyTwo** [comment]
Uh-oh. On what device are you and on what architecture?

**Comment by ghost** [comment]
The Oneplus 3t ARM64

**Comment by TronFortyTwo** [comment]
The crash is due to the deprecated Oxide webview not being available in arm64 images. I am working to move to QtWebEngine so that it would work

**Comment by TronFortyTwo** [comment]
Version 2.1.0 has been bublished for ARM64 and AMD64, fixing the crash. It is not yet 100% stable so I have not published for armhf too yet. Good reading!
