### ISSUE TITLE
Support CBR format 

### ISSUE THREAD

**Issue by padraic7a** [TronFortyTwo/sturmreader#19]
It would be great to be able to read CBRs.

As far as I understand it CBZ support was integrated using quazip. 

I wonder if this might provide the basis for similar functionality? 
https://github.com/ArchangelSDY/QtRAR

**Comment by TronFortyTwo** [comment]
Thanks for the valid suggestion!
With the calibre branch, Sturm Reader is going to use calibre as backend to support more formats and ebooks with DRM. It's still not fully functional, but you can test it if you want...

**Comment by padraic7a** [comment]
Cool, I'll try to build the calibre branch and give it a go. I'll respond with Issues if I do get to test.

**Comment by TronFortyTwo** [comment]
Great!
