### ISSUE TITLE
Problem building Calibre branch: "Package 'calibre:armhf' has no installation candidate"

### ISSUE THREAD

**Issue by padraic7a** [TronFortyTwo/sturmreader#20]
When trying to build the calibre branch I git clone the repository and then

```
$ cd sturmreader 

$ git checkout calibre

$ clickable
```
I then get an error message about "Package 'calibre:armhf' has no installation candidate".

Do you have a PPA I should be using?

Full output from 'clickable' here: https://pastebin.com/BTJkm6Hz
I'm running Ubuntu 18.04.

**Comment by TronFortyTwo** [comment]
Yes this is a known problem with clickable trying to install dependencies, but I don't know how to solve it.
In my workflow I don't get this error. I usually work just using Clickable inside a container on the device, at the end of the day is the same thing. Just connect a device and enter a shell with `$ clickable shell`
Create a debootstrap container in the device `$ sudo debootstrap xenial containername`
It will take around 5/10 minutes. Enter it `$ sudo chroot containername`. You will need to install the packages you usually use for development such as git, clickable, and everything.
Then do the normal steps:

```

$ cd sturmreader

$ git checkout calibre

$ clickable --container-mode # Remember to use --container-mode

```

NOTE 1:
When installing packages in the container you may need to enable universe and multiverse repository in /etc/apt/sources.list

NOTE 2:
You can use a Libertine container too, but I have not tested them

NOTE 3:
Hopefully it's my machine, but in the last days I got tons of conflicting packages errors when trying to install clickable and calibre. Still investigating the issue. I suggest to you however to install clickable from the PPA to avoid some possible headache anyway

**Comment by padraic7a** [comment]
Ok, I'll give that a go in the coming days when I get a chance.
In the meantime I wonder if you have a prebuilt click for the M10 I could test?

**Comment by TronFortyTwo** [comment]
Unfortunately I lost it... If I get to build one I'll share it

**Comment by TronFortyTwo** [comment]
calibre branch is getting outdated. Since calibre 5.0 is out with python3 support, would be better to restart from scratch with that.
