### ISSUE TITLE
Buggy importing of e-books

### ISSUE THREAD

**Issue by cibersheep** [TronFortyTwo/sturmreader#22]
Tested on Arale, Cooler with several ePub 2.1 (that worked in previous versions)

- Open Teleports / File manager
- Select Sturmreader as target app

Current behaviour:
1) It imports the file
2) Tries to load the file but keeps loading

- Book shows in the main menu but they don't open
- TOC is visible while book is tried to be loaded but not navegable

http://paste.ubuntu.com/p/8PMTvs9GJ4/

**Comment by TronFortyTwo** [comment]
Thanks for the report! This seems a critic issue, I'll investigate it asap

**Comment by TronFortyTwo** [comment]
As a temporary workaround, add books using the + icon in the Sturm Reader app.

**Comment by TronFortyTwo** [comment]
Hopefully this issue should be fixed in 2.1.2

**Comment by cibersheep** [comment]
T H A N K S !
It works as a charm <3
