### ISSUE TITLE
UI Scales wrong 

### ISSUE THREAD

**Issue by cibersheep** [TronFortyTwo/sturmreader#29]
Looks like with 3.0x UI elements scale wrong (except for ContentHub Import icon)
- Big icons
- Big text (even in ContentHub)

Top Sturm Reader vs bottom System Settings
![imatge](https://user-images.githubusercontent.com/6640041/92303564-4de11f00-ef76-11ea-8072-44fc3e6b7b17.png)

**Comment by TronFortyTwo** [comment]
Thanks for pointing out! Changing toolkit I missed adjusting some UI stuff. Hopefully I adjusted them in 3.0.3. If there is still something off your reports are welcome :)

**Comment by cibersheep** [comment]
I was very excited to see 3.0.3 update... 
I think some of the head titles are still a bit bigger... but I can come back with proper sizes...

Thanks for your work!!
