### ISSUE TITLE
E-Book Repository Add/Remove Module

### ISSUE THREAD

**Issue by wayneoutthere** [TronFortyTwo/sturmreader#3]
Feature request:
Where: After entering the + from the library section where you add books from repositories

what:
1. Ability to easily add new repositories without a central database of repositories (personal secret repository?) via local device somehow (ie. send a repository via bluetooth via Serval project)
2. Ability to add a new repository from a central repository database according to what you would like on the list
3. Ability to remove a repository any time

**Comment by TronFortyTwo** [comment]
Since version 2.1.1 we don't anymore have the ebook repository page, I close this
