### ISSUE TITLE
[UI] Section on the top

### ISSUE THREAD

**Issue by cibersheep** [TronFortyTwo/sturmreader#30]
Here just a friendly UI idea :)

In version 3.0x you moved the Sections to the bottom, in the [HIG is recommended](http://docs.ubports.com/en/latest/humanguide/app-layout/app-main-view.html#tabbed-content) to place them under Header

![imatge](https://user-images.githubusercontent.com/6640041/92303649-3f473780-ef77-11ea-80ce-7e37dae890a0.png)

**Comment by TronFortyTwo** [comment]
Thanks for pointing out! I am not really an UI guy ;-)
In version 3.0.3 I moved it at the top

**Comment by cibersheep** [comment]
You know how to make a sheep happy ^__^
