### ISSUE TITLE
Sturmreader no more translated

### ISSUE THREAD

**Issue by ghost** [TronFortyTwo/sturmreader#34]
Sturmreader seems no more translated since version 3.0 refoactoring, even if some translations are at 100% (here French).
Tested with OTA-13 stable and FP2.

**Comment by TronFortyTwo** [comment]
You mean that translations are completely ignored, or some strings are still translated?

**Comment by ghost** [comment]
I mean completely ignored
![screenshot20201003_155544152](https://user-images.githubusercontent.com/17686836/94993424-3014d300-0591-11eb-864d-5b484b6e214a.png)
![screenshot20201003_155512372](https://user-images.githubusercontent.com/17686836/94993426-31de9680-0591-11eb-8f0b-570b3025f7c6.png)

**Comment by TronFortyTwo** [comment]
Thanks for letting me know! Somehow the translation system is broken, but I am not sure why. Hope to fix it soon

**Comment by TronFortyTwo** [comment]
It took a bit to pinpoint the problem... But with version 3.1.2 should be fixed

**Comment by ghost** [comment]
Yes, it's working again! Thanks a lot.
