### ISSUE TITLE
CBZ position is not remembered

### ISSUE THREAD

**Issue by cibersheep** [TronFortyTwo/sturmreader#35]
Reopeing a cbz file will start always on the first page

**Comment by TronFortyTwo** [comment]
Thanks for the report!
Hopefully I will soon revamp CBZ support integrating it into the new wip pdf engine

**Comment by cibersheep** [comment]
Ouuuuhh... that sounds exiting!
Thanks for all the work

**Comment by TronFortyTwo** [comment]
Latest code on master now converts CBZ files to PDF when importing them, this will fix this issue.
