### ISSUE TITLE
Default parameters not loaded when opening a book

### ISSUE THREAD

**Issue by ghost** [TronFortyTwo/sturmreader#38]
How to reproduce:
Open a book.
Select Parameters, set the color, police size, margins, etc, select Define as default.
Select Close.
Close Sturm Reader.
Open Sturm Reader and open the same book.
Custom parameters are not loaded.

Expected behavior:
Custom parameters automatically loaded at start.

Configuration:
FP2 OTA 15 stable

**Comment by TronFortyTwo** [comment]
Thanks for the report! I'll check that

**Comment by TronFortyTwo** [comment]
This issue should hopefully be fixed in version 3.3.0
If it persist in your case, let me know! :D
