### ISSUE TITLE
CBZ with folder doesn't get imported

### ISSUE THREAD

**Issue by cibersheep** [TronFortyTwo/sturmreader#47]
Having a cbz file like:
```
file.cbz
 - vol01/
   - pic01.jpg
 - vol02/
   - pic01.jpg
 ```
gives errror while being converted to pdf with error 
```
unsupported image file: /home/phablet/.local/share/sturmreader.emanuelesorce/Books/file.cbz_TEMP/vol01/
qml: error converting
qml: fileType: CBZ
```

**Comment by cibersheep** [comment]
Workaround: zip the images without folder.
PS: The pdf view of cbz is great :) specially landscape view and zooming <3

**Comment by TronFortyTwo** [comment]
Thanks for the report! You are right, CBZ converter doesn't scan for subfolders at the moment. Added to todo list

**Comment by TronFortyTwo** [comment]
If possible, can you send or link a CBZ file with this problem so that I will be able to test a fix?

**Comment by TronFortyTwo** [comment]
This is fixed, and will be included in next release

**Comment by cibersheep** [comment]
I'm officially excited and dancing. Just for your information :P
