### ISSUE TITLE
Doesn`t work on Xenial

### ISSUE THREAD

**Issue by lfortanet** [TronFortyTwo/sturmreader#7]
Hi, the program open and run, but when you try to open a book doesn`t show it. Can you recompile for 16/04 Xenial, please?
thanks.

**Comment by advocatux** [comment]
As of today (2018-07-03) there's is a new Sturm Reader version for xenial on the OpenStore, so maybe you can close this issue.

**Comment by TronFortyTwo** [comment]
😀
