### ISSUE TITLE
"Get books" button doesn't work

### ISSUE THREAD

**Issue by advocatux** [TronFortyTwo/sturmreader#8]
Sturm Reader, version 2.0.6 on xenial.

When you don't have any book on your phone, this default screen shows when opening the app

![sturmreader](https://user-images.githubusercontent.com/30233652/42237173-5d634282-7efd-11e8-8e81-a53b5e9d316e.jpg)
so the first thing a user probably does is to click on that "Get books" (Obtener libros) button but it doesn't work. Every time I click on that button I can see this error on the log:
`file:///opt/click.ubuntu.com/sturmreader.emanuelesorce/2.0.6/ui/LocalBooks.qml:698: TypeError: Cannot call method 'push' of null`

**Comment by TronFortyTwo** [comment]
Thanks!

**Comment by TronFortyTwo** [comment]
Just fixed it. Next version will ship with this fixed. (Probably the plus version has this fixed already)

**Comment by TronFortyTwo** [comment]
Fix released in version 2.0.6.1
