### ISSUE TITLE
OpenStore on xenial installs wrong Sturm Reader version

### ISSUE THREAD

**Issue by advocatux** [TronFortyTwo/sturmreader#9]
After a fresh 16.04 devel (2018-07-07) install, `wipe` included, on a BQ E4.5 (krillin) I proceed to open the OpenStore app to install Sturm Reader.

The issue is that 2.0.5 is the version I got installed on my phone, not 2.0.6

Funny enough, after installing Sturm Reader using OpenStore, OpenStore complains about "the installed version doesn't come from OpenStore blablabla...".

**Comment by TronFortyTwo** [comment]
This is an issue with the OpenStore itself I think - maybe caused by the fact that 2.0.6 is only availablle for Xenial and not for Vivid. I do not know what can I do about this...
